### ISSUE TITLE
(small) mistake in documentation 

### ISSUE THREAD

**Issue by thomasverbeke** [mayeranalytics/pySX127x#1]
I think there is a (small) mistake in your documentation in board_config.py from line 33

    # Note that the BCOM numbering for the GPIOs is used.
    DIO0 = 22   # RaspPi GPIO 21
    DIO1 = 23   # RaspPi GPIO 22
    DIO2 = 24   # RaspPi GPIO 23
    DIO3 = 25   # RaspPi GPIO 24
    LED  = 18   # RaspPi GPIO 18 connects to the LED on the proto shield
    SWITCH = 4  # RaspPi GPIO 4 connects to a switch

Should say DIO0 = 22   # RaspPi GPIO 22 instead of 21

**Comment by mayeranalytics** [comment]
Hi Thomas,
thank you for the feedback! Yes, you are right. It shall be fixed.
Regards
Markus
