### ISSUE TITLE
SX1301

### ISSUE THREAD

**Issue by afeezaziz** [mayeranalytics/pySX127x#10]
Since the project is going to be named pyLora, are you going to make the project to work with SX1301? 

I did try this with SX1301 using Multitech's Lora on Raspberry Pi but it did not work.

**Comment by mayeranalytics** [comment]
The Semtech SX1301 datasheet is not publicly available, as far as I know. So I don’t even know what exactly this chip does. But it would be nice to add it, eventually.

**Comment by mayeranalytics** [comment]
The SX1301 is a " digital baseband chip". There is little relation to the sx127x as you can see by looking at the SPI interface.
