### ISSUE TITLE
rssi value calculation

### ISSUE THREAD

**Issue by dimka-rs** [mayeranalytics/pySX127x#15]
Rssi is currently calculated as

>  return v - 157

which is correct for High Frequency only
See  "5.5.5. RSSI and SNR in LoRa TM Mode" (page 87)

RSSI (dBm) = -157 + Rssi, (when using the High Frequency (HF) port)
or
RSSI (dBm) = -164 + Rssi, (when using the Low Frequency (LF) port)

**Comment by mayeranalytics** [comment]
fixed

**Comment by mayeranalytics** [comment]
fixed
