### ISSUE TITLE
I can't receive LoRa messages

### ISSUE THREAD

**Issue by sabrine2020** [mayeranalytics/pySX127x#17]
Hello, 
I am using Raspberry pi with inair9 module. I tried to use your library to communicate with the radio module. The tests pass, the radio module seems communicating.
when I lunch the program:
sudo python rx_cont.py -r CR4_5 -s 12 -f 868

I only get the RSSI going up and down. I received no messages.
I am using libelium module to send messages on the correspondant channel and spreading factor and data rate.

however I only notice that the RSSI go down (from -110 to -20) when I sent messages using libelium.
Any idea of what have I missed in the configuration to be able to receive messages?

Thanks!

**Comment by pointhi** [comment]
I had a similar problem. In my case, I made wrong changes to the board files which causes the rx interrupts to be not detected. Do you have a RX LED? If yes, does it light up after a package was sent by your other station?
