### ISSUE TITLE
OTAA or ABP support?

### ISSUE THREAD

**Issue by bogdanoniga** [mayeranalytics/pySX127x#20]
Your library supports OTAA or ABP?

**Comment by mayeranalytics** [comment]
This library is some levels below LoraWAN and LoraMac, it is not concerned with OTAA or ABP.

**Comment by jeroennijhof** [comment]
@bogdanoniga I have ported LoRaWAN to python which support OTAA and ABP, check https://github.com/jeroennijhof/LoRaWAN

**Comment by bogdanoniga** [comment]
@jeroennijhof this is wonderful, thank you for letting me know
