### ISSUE TITLE
pySX127 @ 915 Mhz, files to be changed

### ISSUE THREAD

**Issue by pyflier** [mayeranalytics/pySX127x#27]
Hi There

I'm wondering if someone can help me to sort out what other changes must be applied to work with a SX1276 LoRa Module,  915MHz.
Also just wondering in class BOARD, what exactly the function of SWITCH is?
Thanks in advance

**Comment by mayeranalytics** [comment]
SWITCH was a push button (brilliant naming, switch...) witch was connected to the board. It was used to trigger TXs.
