### ISSUE TITLE
Question on the code, use of the registers

### ISSUE THREAD

**Issue by BMarvi** [mayeranalytics/pySX127x#29]
@mayeranalytics 

    return self.spi.xfer([register_address & 0x7F, 0])[1]
    return self.spi.xfer([register_address | 0x80, val])[1]

can't understand  the  "& 0x7F"  and   "| 0x80" part....
why is necessary to modify the register address?

**Comment by mayeranalytics** [comment]
Have a look at section 4.3 of the datasheet:

The first byte is the address byte. It is comprises:

- A wnr bit, which is 1 for write access and 0 for read access.
- Then 7 bits of address, MSB first.

I.e. the intention to read or write is encoded in the highest bit of the address byte. The `.. & 0x7F` and `.. | 0x80` set the highest bit to `0` or `1`.
