### ISSUE TITLE
MAX_PAYLOAD_LENGTH typo

### ISSUE THREAD

**Issue by thomasverbeke** [mayeranalytics/pySX127x#3]
In constants.py clss REG class LORA both PAYLOAD_LENGTH and MAX_PAYLOAD_LENGTH are indicating register 0x22. I assume this is a typo, MAX PAYLOAD should refer to reg 0x23.

**Comment by mayeranalytics** [comment]
I appreciate all your input. Yes it should be 0x23. Fixed.
