### ISSUE TITLE
Request, not issue. BeagleBone support

### ISSUE THREAD

**Issue by blkist** [mayeranalytics/pySX127x#33]
Hi, I'm sorry for putting this in the issues, but I'm new to Github, and I wasn't sure how to send you a request. Is there any way this can be converted to use the Beaglebone platform instead of the Raspberry Pi? I was thinking maybe you would use the Adafruit BBIO library instead of RPi.GPIO? I'm not a developer by any stretch, but I was just wondering what it would take to do something like that? I have a 433Mhz LoRa RFM9 board that uses SPI, but I'm not sure how to get it to talk to my Beaglebone Blue. I wired up the MOSI/MISO, CLK, and CS correctly, but I don't know how to send or listen for packets with it. Any help or comments would be appreciated.

**Comment by mayeranalytics** [comment]
Hi,
you have to modify the file `pySX127x/board_config.py` and adapt it to the bbone and your wiring.
Just go through `board_config.py` and replace the RPi.* calls.
This is quite straightforward, except maybe the event_detect business. Event_detect registers a python function to be called when an interrupt occurs on an input pin. BBIO can do this.
