### ISSUE TITLE
LoraWan

### ISSUE THREAD

**Issue by MartijnBraam** [mayeranalytics/pySX127x#5]
I have a SX127x module (http://modtronix.com/inair9B.html) and trying to connect to the lorawan network. 

what parts of the lorawan communication is handled by this module? In the LoRaWan specification I see the Radio PHY layer, PHYPayload layer, MACPayload layer and FHDR. What part am I sending with the write_payload command?

**Comment by dmahony** [comment]
the inair9b can connect to LoRawan but not with this library, you should
check out this: https://github.com/Lora-net
I think thats closer to what you are after.

**Comment by MartijnBraam** [comment]
Thank you for the information
