### ISSUE TITLE
Microchip

### ISSUE THREAD

**Issue by thomasverbeke** [mayeranalytics/pySX127x#8]
"Microchip transceiver IC

Likewise Microchip has the chip RN2483"

Microchip only exposes an uart interface so SPI is going to be useless here I think.

**Comment by mayeranalytics** [comment]
Yes indeed. SPI is useless. Good point.
But at a certain abstraction level these serial interfaces SPI, I2C, UART become interchangeable. I think this is pretty much the case here. Rip out the SPI and plug in UART.
