### ISSUE TITLE
build folder

### ISSUE THREAD

**Issue by byrann** [mayeranalytics/pySX127x#9]
am working with this code on ORANGE PI .
I have problems with RPI.GPIO
and I think that I need a build folder to continue.
any ideas ??

**Comment by mayeranalytics** [comment]
I'm not sure what you mean with build folder, and as I'm not familiar with the Orange Pi I can't say much about the specifics. But I'm pretty sure the pinout and naming is completely different on the Orange Pi. That shouldn't stop you, though.
In general I'd suggest to get the GPIO and the SPI working properly with the library of choice for your board. Then GPIOs are easily tested with a little toggle script and a voltmeter. Debugging SPI is harder, but there's the loopback test that I recommend to do first if there's any trouble with SPI. See [here](https://www.raspberrypi.org/documentation/hardware/raspberrypi/spi/README.md).
